# Generated by Django 4.2.7 on 2024-01-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='manifesto',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
